### ISSUE TITLE
Dataset and benchmark release

### ISSUE THREAD

**Issue by Buzz-Beater** [IT3DEgo/IT3DEgo#2]
Thanks for the great work, I was wondering if there is a timeline for dataset and benchmark release.

**Comment by IT3DEgo** [comment]
Thanks for your interest! We are currently in the final stage of cleaning and uploading to the server. The dataset and code will be released very soon, most likely in the next few weeks.

**Comment by IT3DEgo** [comment]
> Thanks for the great work, I was wondering if there is a timeline for dataset and benchmark release.

Thanks for your interest! We are currently in the final stage of cleaning and uploading to the server. The dataset and code will be released very soon, most likely in the next few weeks.
